---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitops-metrics-server
  description: 'Kubernetes Metrics Server — enables HPA and kubectl top'
  tags:
    - kubernetes
    - homelab
    - infrastructure
  annotations:
    github.com/project-slug: cassioliveiram/gitops.metrics-server
    backstage.io/kubernetes-id: homelab-talos
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: homelab
